//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DqdLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DqdK22CNTLesson09DbEntities2 : DbContext
    {
        public DqdK22CNTLesson09DbEntities2()
            : base("name= DqdK22CNTLesson09DbEntities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<DqdKhoa> DqdKhoa { get; set; }
        public virtual DbSet<DqdSinhVien> DqdSinhVien { get; set; }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }

        internal object Entry(DqdKhoa lttKhoa)
        {
            throw new NotImplementedException();
        }
    }
}