//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DqdLesson09.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DqdSinhVien
    {
        public string DqdMaSV { get; set; }
        public string DqdHoSV { get; set; }
        public string DqdTenSV { get; set; }
        public Nullable<System.DateTime> DqdNgaySinh { get; set; }
        public Nullable<bool> DqdPhai { get; set; }
        public string DqdPhone { get; set; }
        public string DqdEmail { get; set; }
        public string DqdMaKH { get; set; }

        public virtual DqdKhoa DqdKhoa { get; set; }
    }
}