//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DqdLesson09.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DqdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DqdKhoa()
        {
            this.LttSinhVien = new HashSet<DqdSinhVien>();
        }

        public string DqdMaKH { get; set; }
        public string DqdTenKH { get; set; }
        public Nullable<bool> DqdTrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DqdSinhVien> DqdSinhVien { get; set; }
    }
}